// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AppIntent
    {
        /// <summary>
        /// Initializes a new instance of the AppIntent class.
        /// </summary>
        public AppIntent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppIntent class.
        /// </summary>
        public AppIntent(IList<ExtendedFeatureData> extendedFeaturesData = default(IList<ExtendedFeatureData>), ClModelDescriptor clModelData = default(ClModelDescriptor), string intent = default(string), double? score = default(double?))
        {
            ExtendedFeaturesData = extendedFeaturesData;
            ClModelData = clModelData;
            Intent = intent;
            Score = score;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extendedFeaturesData")]
        public IList<ExtendedFeatureData> ExtendedFeaturesData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clModelData")]
        public ClModelDescriptor ClModelData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intent")]
        public string Intent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
