// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClModelDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the ClModelDescriptor class.
        /// </summary>
        public ClModelDescriptor()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClModelDescriptor class.
        /// </summary>
        public ClModelDescriptor(IList<double?> bias = default(IList<double?>), IList<ClSparseVector> weights = default(IList<ClSparseVector>))
        {
            Bias = bias;
            Weights = weights;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bias")]
        public IList<double?> Bias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weights")]
        public IList<ClSparseVector> Weights { get; set; }

    }
}
