// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClSparseVector
    {
        /// <summary>
        /// Initializes a new instance of the ClSparseVector class.
        /// </summary>
        public ClSparseVector()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClSparseVector class.
        /// </summary>
        public ClSparseVector(int? numFeatures = default(int?), IList<int?> indices = default(IList<int?>), IList<double?> values = default(IList<double?>))
        {
            NumFeatures = numFeatures;
            Indices = indices;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numFeatures")]
        public int? NumFeatures { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indices")]
        public IList<int?> Indices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public IList<double?> Values { get; set; }

    }
}
