// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CompositeEntity
    {
        /// <summary>
        /// Initializes a new instance of the CompositeEntity class.
        /// </summary>
        public CompositeEntity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CompositeEntity class.
        /// </summary>
        public CompositeEntity(string parentType = default(string), string value = default(string), IList<CompositeChild> children = default(IList<CompositeChild>))
        {
            ParentType = parentType;
            Value = value;
            Children = children;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentType")]
        public string ParentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "children")]
        public IList<CompositeChild> Children { get; set; }

    }
}
