// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExtendedFeatureData
    {
        /// <summary>
        /// Initializes a new instance of the ExtendedFeatureData class.
        /// </summary>
        public ExtendedFeatureData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExtendedFeatureData class.
        /// </summary>
        public ExtendedFeatureData(string featureText = default(string), int? featureIndex = default(int?), double? featureValue = default(double?))
        {
            FeatureText = featureText;
            FeatureIndex = featureIndex;
            FeatureValue = featureValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "featureText")]
        public string FeatureText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "featureIndex")]
        public int? FeatureIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "featureValue")]
        public double? FeatureValue { get; set; }

    }
}
