// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace jschweda.luisDemo.client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SentimentResult
    {
        /// <summary>
        /// Initializes a new instance of the SentimentResult class.
        /// </summary>
        public SentimentResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SentimentResult class.
        /// </summary>
        public SentimentResult(string label = default(string), double? score = default(double?))
        {
            Label = label;
            Score = score;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
